### ISSUE TITLE
TestRoundTripAllLevels fails?

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#132]
The test file TestRoundTripAllLevels fails locally for me with
```
rabbitescape.engine.menu.LevelsMenu$ErrorLoadingLevelList: menu.LevelsMenu.ErrorLoadingLevelList {cause=null}
	at rabbitescape.engine.menu.LevelsMenu.levelsInResource(LevelsMenu.java:73)
	at rabbitescape.engine.menu.LevelsMenu.menuItems(LevelsMenu.java:36)
	at rabbitescape.engine.menu.LevelsMenu.<init>(LevelsMenu.java:25)
	at rabbitescape.engine.menu.MenuTargets.levels(MenuTargets.java:8)
	at rabbitescape.engine.menu.MenuDefinition.mainMenu(MenuDefinition.java:23)
	at rabbitescape.engine.menu.MenuDefinition.mainMenu(MenuDefinition.java:11)
	at rabbitescape.engine.TestRoundTripAllLevels.Round_trip_all_levels(TestRoundTripAllLevels.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: rabbitescape.engine.util.Util$MissingResource: util.Util.MissingResource {cause=null, name=/rabbitescape/levels/easy/ls.txt}
	at rabbitescape.engine.util.Util.resourceLines(Util.java:572)
	at rabbitescape.engine.menu.LevelsMenu.levelsInResource(LevelsMenu.java:66)
	... 29 more
```
I think this is because ls.txt is in the .gitignore file.

**Comment by colonelfazackerley** [comment]
I think make should create the level list file.

**Comment by tttppp** [comment]
Ahh, ok. In that case this is a feature request for a self-contained test! ;-)

I'll close the issue.

**Comment by andybalaam** [comment]
`make` is required before running. If you feel this is too impure I am happy to move tests that require make into a separate set of tests. This set will also include the new tests that levels are soluble,  when we write them.

**Comment by andybalaam** [comment]
On a separate point, I actually plan to name level files after the level names and manually author levelset files so they will replace ls.txt
