### ISSUE TITLE
Bug: text mode: if time steps over completion, get stack trace instead of congratulations

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#146]
``` java
Type 'help' then press return for help.
> 10
World.DontStepAfterFinish {cause=null, worldName=Choppy}
Type 'help' then press return for help.
> 
rabbitescape.engine.World$DontStepAfterFinish: World.DontStepAfterFinish {cause=null, worldName=Choppy}
    at rabbitescape.engine.World.step(World.java:188)
    at rabbitescape.ui.text.TextGameLaunch.run(TextGameLaunch.java:74)
    at rabbitescape.render.Main.launchGame(Main.java:54)
    at rabbitescape.ui.text.TextMenu.level(TextMenu.java:116)
    at rabbitescape.ui.text.TextMenu.handleTarget(TextMenu.java:102)
    at rabbitescape.ui.text.TextMenu.run(TextMenu.java:86)
    at rabbitescape.ui.text.TextMain.run(TextMain.java:35)
    at rabbitescape.ui.text.TextMain.main(TextMain.java:30)
```

I think entering 10 time steps was my problem. During that time, they all left.

**Comment by tttppp** [comment]
Related to #145.

**Comment by andybalaam** [comment]
Yes, a bug

**Comment by andybalaam** [comment]
The behaviour has changed, but is still a bug (I think).  Now we get:

    Solution failed: world has stopped (state: WON) but there are more solution commands

**Comment by andybalaam** [comment]
I think this is fixed; let me know if not.
