### ISSUE TITLE
Can't tell which level has a problem

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#147]
I added a solution to hard 1 and ran "make test"
```
test:
    [junit] Testsuite: rabbitescape.engine.TestAllActiveLevels
    [junit] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.78 sec
    [junit] Testcase: All_levels_load_and_round_trip took 0.545 sec
    [junit] Testcase: All_solutions_are_correct took 0.171 sec
    [junit] 	Caused an ERROR
    [junit] solution.InvalidSolution {cause=null, message=Solution 0 did not cause WON at instruction 34}
    [junit] rabbitescape.engine.solution.InvalidSolution: solution.InvalidSolution {cause=null, message=Solution 0 did not cause WON at instruction 34}
    [junit] 	at rabbitescape.engine.solution.SolutionRunner$1.caseTargetState(SolutionRunner.java:81)
    [junit] 	at rabbitescape.engine.solution.TargetState.typeSwitch(TargetState.java:70)
    [junit] 	at rabbitescape.engine.solution.SolutionRunner.performInstruction(SolutionRunner.java:50)
    [junit] 	at rabbitescape.engine.solution.SolutionRunner.runSolution(SolutionRunner.java:20)
    [junit] 	at rabbitescape.engine.TestAllActiveLevels.All_solutions_are_correct(TestAllActiveLevels.java:123)
    [junit] 
```
- I think this ouput should tell me which level
- I called it solution.1, it returns solution 0.

The text mode game won output did not have "WON" at the end. If I put 'WON' at the end, it still fails.

**Comment by tttppp** [comment]
I thought I'd seen the solution.0 issue in the past. It was because the Solution objects didn't get the id set in the constructor.

**Comment by andybalaam** [comment]
Yes, 2 problems here: wrong solution Id and no indication of which level failed. The latter can be fixed by catching the exception and throwing a more informative one.

**Comment by tttppp** [comment]
I think this issue is fixed now. Last time I checked I'm pretty sure the exception message contained the level title in it.  (I'm not at a computer now, but remember seeing "Choppy" in a solution checking stack trace).

**Comment by colonelfazackerley** [comment]
I just messed up some levels on master, and the level that failed was clear.
```
    [junit] rabbitescape.engine.solution.SolutionExceptions$RanPastEnd: Solution failed: world has stopped (state: WON) but there are more solution commands at command 15 of solution 2 in hard/level_01.rel:

```

**Comment by andybalaam** [comment]
Brilliant, thanks.

**Comment by colonelfazackerley** [comment]
```
test:
    [junit] Testsuite: rabbitescape.engine.TestAllActiveLevels
    [junit] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.96 sec
    [junit] 
    [junit] Testcase: All_levels_load_and_round_trip took 0.438 sec
    [junit] Testcase: All_solutions_are_correct took 0.481 sec
    [junit] 	Caused an ERROR
    [junit] solution.InvalidAction {action=until:WON, cause=null}
    [junit] rabbitescape.engine.solution.InvalidAction: solution.InvalidAction {action=until:WON, cause=null}
    [junit] 	at rabbitescape.engine.solution.SolutionParser.doMakeAction(SolutionParser.java:99)
    [junit] 	at rabbitescape.engine.solution.SolutionParser.makeAction(SolutionParser.java:65)
    [junit] 	at rabbitescape.engine.solution.SolutionParser.parseCommand(SolutionParser.java:53)
    [junit] 	at rabbitescape.engine.solution.SolutionParser.parse(SolutionParser.java:36)
    [junit] 	at rabbitescape.engine.TestAllActiveLevels.runSolutionString(TestAllActiveLevels.java:139)
    [junit] 	at rabbitescape.engine.TestAllActiveLevels.All_solutions_are_correct(TestAllActiveLevels.java:123)
    [junit] 
```
Found one.

It does tell me that until:WON is the problem, so I can grep for it. Close this again if you think i am being fussy.

**Comment by andybalaam** [comment]
Definitely needs fixing. Nice spot.

**Comment by andybalaam** [comment]
With my latest change:

```
    [junit] Testcase: All_official_levels_work_and_have_winning_solutions took 0.025 sec
    [junit] 	Caused an ERROR
    [junit] solution.SolutionExceptions.UnknownProblem {cause=null, commandIndex=-1, level=level_01, solutionId=1, world=}
    [junit] rabbitescape.engine.solution.SolutionExceptions$UnknownProblem: solution.SolutionExceptions.UnknownProblem {cause=null, commandIndex=-1, level=level_01, solutionId=1, world=}
    [junit] 	at rabbitescape.engine.TestAllActiveLevels.runSolutionString(TestAllActiveLevels.java:197)
    [junit] 	at rabbitescape.engine.TestAllActiveLevels.access$0(TestAllActiveLevels.java:177)
    [junit] 	at rabbitescape.engine.TestAllActiveLevels$3.run(TestAllActiveLevels.java:105)
    [junit] 	at rabbitescape.engine.TestAllActiveLevels.forEachOfficialLevel(TestAllActiveLevels.java:139)
    [junit] 	at rabbitescape.engine.TestAllActiveLevels.All_official_levels_work_and_have_winning_solutions(TestAllActiveLevels.java:34)
    [junit] Caused by: rabbitescape.engine.solution.InvalidAction: solution.InvalidAction {action=foo, cause=null}
    [junit] 	at rabbitescape.engine.solution.SolutionParser.doMakeAction(SolutionParser.java:114)
    [junit] 	at rabbitescape.engine.solution.SolutionParser.makeAction(SolutionParser.java:74)
    [junit] 	at rabbitescape.engine.solution.SolutionParser.parseCommand(SolutionParser.java:55)
    [junit] 	at rabbitescape.engine.solution.SolutionParser.parse(SolutionParser.java:38)
    [junit] 	at rabbitescape.engine.TestAllActiveLevels.runSolutionString(TestAllActiveLevels.java:186)
```
