### ISSUE TITLE
text ui broken

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#175]
-start game
-select token
-exception

```
00 ###########
01 #   Q     #
02 #\      /##
03 ###########
04 #         #
05 #\       O#
06 ###########
   00000000001
   01234567890

dig: 5

Type 'help' then press return for help.
> dig
java.lang.AssertionError: Should not perform wait action
	at rabbitescape.engine.solution.SolutionRunner$1.caseWaitAction(SolutionRunner.java:107)
	at rabbitescape.engine.solution.WaitAction.typeSwitch(WaitAction.java:64)
	at rabbitescape.engine.solution.SolutionRunner.doPerformAction(SolutionRunner.java:102)
	at rabbitescape.engine.solution.SolutionRunner.performAction(SolutionRunner.java:75)
	at rabbitescape.ui.text.InputHandler.handle(InputHandler.java:77)
	at rabbitescape.ui.text.TextGameLaunch.run(TextGameLaunch.java:61)
	at rabbitescape.render.Main.launchGame(Main.java:54)
	at rabbitescape.ui.text.TextMenu.level(TextMenu.java:116)
	at rabbitescape.ui.text.TextMenu.handleTarget(TextMenu.java:102)
	at rabbitescape.ui.text.TextMenu.run(TextMenu.java:86)
	at rabbitescape.ui.text.TextMain.run(TextMain.java:35)
	at rabbitescape.ui.text.TextMain.main(TextMain.java:30)
```

**Comment by andybalaam** [comment]
Looks like I broke everything again with my opinionated awkwardness. I will look asap sorry.

**Comment by andybalaam** [comment]
This explains why you didn't understand runSolution - I had not converted it to the new way of working.  I will do that, but reverting for now since master should never be broken.

**Comment by andybalaam** [comment]
I have now removed the underlying cause of this problem - we now process SolutionActions into SolutionTimeSteps everywhere we use them.

Next job: automated test that checks text menu works.
