### ISSUE TITLE
ReLruCache cannot be resolved to a type

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#225]
```
BUILD SUCCESSFUL
Total time: 1 second
java -cp rabbit-escape-engine/bin/:rabbit-escape-render/bin/:rabbit-escape-ui-text/bin/:rabbit-escape-ui-swing/bin/ rabbitescape.ui.swing.SwingMain
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	ReLruCache cannot be resolved to a type
	ReLruCache cannot be resolved to a type
	ReLruCache cannot be resolved to a type
	ReLruCache cannot be resolved to a type
	ReLruCache cannot be resolved to a type

	at rabbitescape.render.BitmapCache.<init>(BitmapCache.java:9)
	at rabbitescape.ui.swing.SwingMain.main(SwingMain.java:61)
Makefile:258: recipe for target 'rungui' failed
```

Perhaps a file was missed with git add?

**Comment by andybalaam** [comment]
Try `make clean all` ?
The file should be there: https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-render/src/rabbitescape/render/ReLruCache.java

**Comment by colonelfazackerley** [comment]
Just realised I had not tried make clean. Sorry.

I will try later.

**Comment by colonelfazackerley** [comment]
make clean and its fine. [gets coat]

**Comment by andybalaam** [comment]
:-)

**Comment by andybalaam** [comment]
I think this is just something you have to put up with in java. It doesn't rebuild things that depend on things it is rebuilding. It's by design to make builds faster and it works 90% of the time.
