### ISSUE TITLE
Can't start level on Swing UI - NoSuchMethodError

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#293]
When trying to `make rungui` using the latest master (0896739c677715422d1bd47b4d498d2cbb2b57ea) everything seems fine until I try to start a level. Then I get a blank Swing screen, and the following stack trace:
```
java -cp rabbit-escape-engine/bin/:rabbit-escape-render/bin/:rabbit-escape-ui-text/bin/:rabbit-escape-ui-swing/bin/ rabbitescape.ui.swing.SwingMain
java.lang.NoSuchMethodError: rabbitescape.engine.util.Util.chain(Ljava/lang/Iterable;Ljava/lang/Iterable;)Ljava/lang/Iterable;
	at rabbitescape.render.AnimationLoader.animationFilesInResource(AnimationLoader.java:66)
	at rabbitescape.render.AnimationLoader.listAll(AnimationLoader.java:86)
	at rabbitescape.render.AnimationCache.<init>(AnimationCache.java:13)
	at rabbitescape.ui.swing.SwingGraphics.<init>(SwingGraphics.java:109)
	at rabbitescape.ui.swing.SwingGameLaunch.<init>(SwingGameLaunch.java:94)
	at rabbitescape.ui.swing.SwingSingleGameEntryPoint.createGameLaunch(SwingSingleGameEntryPoint.java:122)
	at rabbitescape.render.SingleGameEntryPoint.launchGame(SingleGameEntryPoint.java:52)
	at rabbitescape.ui.swing.MenuUi$1.doInBackground(MenuUi.java:370)
	at rabbitescape.ui.swing.MenuUi$1.doInBackground(MenuUi.java:364)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tttppp** [comment]
When doing the same with v0.7.1 everything is fine.

**Comment by colonelfazackerley** [comment]
make clean first?

**Comment by tttppp** [comment]
Win! Thanks.

**Comment by colonelfazackerley** [comment]
I have done that several times...

**Comment by andybalaam** [comment]
It's basically Java's fault. I don't know how to avoid it except cleaning every time.
