### ISSUE TITLE
Git fighting over Android studio project files

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#318]
I suggest using gitignore on the '' rabbit-escape-ui-android/.idea" directory and maybe a few other files. Put the content from there in a zip that can be downloaded from github to get folk started.

**Comment by colonelfazackerley** [comment]
#314

**Comment by andybalaam** [comment]
It would be nice to do better than that. The IDEA folks reckon you can share quite a lot of stuff from that directory. It includes e.g. code formatting and warning settings that weer would like to share. One problem seems to be that it changes when you get a new version of Android studio. If that is the main problem I am happy to check in often and tell people to keep up to date if they don't want to ignore idea stuff.

**Comment by andybalaam** [comment]
If we get some basic instructions done as specified in #319 and #320 then I think we should .gitignore .idea.  Hopefully we can export some code formatting and warning settings and show how to import them during setup.

**Comment by andybalaam** [comment]
I do hate setup steps though, so if we can provide Makefile targets that make things right, that would be better.

**Comment by colonelfazackerley** [comment]
The diff from my latest studio install
```diff
diff --git a/rabbit-escape-ui-android/.idea/codeStyleSettings.xml b/rabbit-escape-ui-android/.idea/codeStyleSettings.xml
index 436aee6..ba48988 100644
--- a/rabbit-escape-ui-android/.idea/codeStyleSettings.xml
+++ b/rabbit-escape-ui-android/.idea/codeStyleSettings.xml
@@ -34,6 +34,34 @@
         <AndroidXmlCodeStyleSettings>
           <option name="USE_CUSTOM_SETTINGS" value="true" />
         </AndroidXmlCodeStyleSettings>
+        <Objective-C-extensions>
+          <option name="GENERATE_INSTANCE_VARIABLES_FOR_PROPERTIES" value="ASK" />
+          <option name="RELEASE_STYLE" value="IVAR" />
+          <option name="TYPE_QUALIFIERS_PLACEMENT" value="BEFORE" />
+          <file>
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="Import" />
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="Macro" />
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="Typedef" />
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="Enum" />
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="Constant" />
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="Global" />
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="Struct" />
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="FunctionPredecl" />
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="Function" />
+          </file>
+          <class>
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="Property" />
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="Synthesize" />
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="InitMethod" />
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="StaticMethod" />
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="InstanceMethod" />
+            <option name="com.jetbrains.cidr.lang.util.OCDeclarationKind" value="DeallocMethod" />
+          </class>
+          <extensions>
+            <pair source="cpp" header="h" />
+            <pair source="c" header="h" />
+          </extensions>
+        </Objective-C-extensions>
         <XML>
           <option name="XML_LEGACY_SETTINGS_IMPORTED" value="true" />
         </XML>
@@ -50,5 +78,4 @@
     </option>
     <option name="PREFERRED_PROJECT_CODE_STYLE" value="Default (1)" />
   </component>
-</project>
-
+</project>
\ No newline at end of file
diff --git a/rabbit-escape-ui-android/.idea/gradle.xml b/rabbit-escape-ui-android/.idea/gradle.xml
index fe865d3..261ec28 100644
--- a/rabbit-escape-ui-android/.idea/gradle.xml
+++ b/rabbit-escape-ui-android/.idea/gradle.xml
@@ -5,7 +5,8 @@
       <GradleProjectSettings>
         <option name="distributionType" value="LOCAL" />
         <option name="externalProjectPath" value="$PROJECT_DIR$" />
-        <option name="gradleHome" value="$APPLICATION_HOME_DIR$/gradle/gradle-2.2.1" />
+        <option name="gradleHome" value="$APPLICATION_HOME_DIR$/gradle/gradle-2.8" />
+        <option name="gradleJvm" value="1.7" />
         <option name="modules">
           <set>
             <option value="$PROJECT_DIR$" />
@@ -15,5 +16,4 @@
       </GradleProjectSettings>
     </option>
   </component>
-</project>
-
+</project>
\ No newline at end of file
diff --git a/rabbit-escape-ui-android/.idea/misc.xml b/rabbit-escape-ui-android/.idea/misc.xml
index 6e922b2..fe18c85 100644
--- a/rabbit-escape-ui-android/.idea/misc.xml
+++ b/rabbit-escape-ui-android/.idea/misc.xml
@@ -27,7 +27,7 @@
       </value>
     </option>
   </component>
-  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_6" assert-keyword="true" jdk-15="true" project-jdk-name="1.6" project-jdk-type="JavaSDK">
+  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_6" assert-keyword="true" jdk-15="true" project-jdk-name="1.7" project-jdk-type="JavaSDK">
     <output url="file://$PROJECT_DIR$/build/classes" />
   </component>
   <component name="masterDetails">
@@ -46,5 +46,4 @@
       </state>
     </states>
   </component>
-</project>
-
+</project>
\ No newline at end of file
diff --git a/rabbit-escape-ui-android/app/app.iml b/rabbit-escape-ui-android/app/app.iml
index fe74647..b051112 100644
--- a/rabbit-escape-ui-android/app/app.iml
+++ b/rabbit-escape-ui-android/app/app.iml
@@ -9,11 +9,15 @@
     <facet type="android" name="Android">
       <configuration>
         <option name="SELECTED_BUILD_VARIANT" value="debug" />
+        <option name="SELECTED_TEST_ARTIFACT" value="_android_test_" />
         <option name="ASSEMBLE_TASK_NAME" value="assembleDebug" />
         <option name="COMPILE_JAVA_TASK_NAME" value="compileDebugSources" />
-        <option name="ASSEMBLE_TEST_TASK_NAME" value="assembleDebugTest" />
-        <option name="SOURCE_GEN_TASK_NAME" value="generateDebugSources" />
-        <option name="TEST_SOURCE_GEN_TASK_NAME" value="generateDebugTestSources" />
+        <option name="ASSEMBLE_TEST_TASK_NAME" value="assembleDebugAndroidTest" />
+        <option name="COMPILE_JAVA_TEST_TASK_NAME" value="compileDebugAndroidTestSources" />
+        <afterSyncTasks>
+          <task>generateDebugAndroidTestSources</task>
+          <task>generateDebugSources</task>
+        </afterSyncTasks>
         <option name="ALLOW_USER_CONFIGURATION" value="false" />
         <option name="MANIFEST_FILE_RELATIVE_PATH" value="/src/main/AndroidManifest.xml" />
         <option name="RES_FOLDER_RELATIVE_PATH" value="/src/main/res" />
@@ -24,7 +28,7 @@
   </component>
   <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_1_6" inherit-compiler-output="false">
     <output url="file://$MODULE_DIR$/build/intermediates/classes/debug" />
-    <output-test url="file://$MODULE_DIR$/build/intermediates/classes/test/debug" />
+    <output-test url="file://$MODULE_DIR$/build/intermediates/classes/androidTest/debug" />
     <exclude-output />
     <content url="file://$MODULE_DIR$">
       <sourceFolder url="file://$MODULE_DIR$/build/generated/source/r/debug" isTestSource="false" generated="true" />
@@ -32,13 +36,13 @@
       <sourceFolder url="file://$MODULE_DIR$/build/generated/source/buildConfig/debug" isTestSource="false" generated="true" />
       <sourceFolder url="file://$MODULE_DIR$/build/generated/source/rs/debug" isTestSource="false" generated="true" />
       <sourceFolder url="file://$MODULE_DIR$/build/generated/res/rs/debug" type="java-resource" />
-      <sourceFolder url="file://$MODULE_DIR$/build/generated/res/generated/debug" type="java-resource" />
-      <sourceFolder url="file://$MODULE_DIR$/build/generated/source/r/test/debug" isTestSource="true" generated="true" />
-      <sourceFolder url="file://$MODULE_DIR$/build/generated/source/aidl/test/debug" isTestSource="true" generated="true" />
-      <sourceFolder url="file://$MODULE_DIR$/build/generated/source/buildConfig/test/debug" isTestSource="true" generated="true" />
-      <sourceFolder url="file://$MODULE_DIR$/build/generated/source/rs/test/debug" isTestSource="true" generated="true" />
-      <sourceFolder url="file://$MODULE_DIR$/build/generated/res/rs/test/debug" type="java-test-resource" />
-      <sourceFolder url="file://$MODULE_DIR$/build/generated/res/generated/test/debug" type="java-test-resource" />
+      <sourceFolder url="file://$MODULE_DIR$/build/generated/res/resValues/debug" type="java-resource" />
+      <sourceFolder url="file://$MODULE_DIR$/build/generated/source/r/androidTest/debug" isTestSource="true" generated="true" />
+      <sourceFolder url="file://$MODULE_DIR$/build/generated/source/aidl/androidTest/debug" isTestSource="true" generated="true" />
+      <sourceFolder url="file://$MODULE_DIR$/build/generated/source/buildConfig/androidTest/debug" isTestSource="true" generated="true" />
+      <sourceFolder url="file://$MODULE_DIR$/build/generated/source/rs/androidTest/debug" isTestSource="true" generated="true" />
+      <sourceFolder url="file://$MODULE_DIR$/build/generated/res/rs/androidTest/debug" type="java-test-resource" />
+      <sourceFolder url="file://$MODULE_DIR$/build/generated/res/resValues/androidTest/debug" type="java-test-resource" />
       <sourceFolder url="file://$MODULE_DIR$/src/debug/res" type="java-resource" />
       <sourceFolder url="file://$MODULE_DIR$/src/debug/resources" type="java-resource" />
       <sourceFolder url="file://$MODULE_DIR$/src/debug/assets" type="java-resource" />
@@ -61,24 +65,19 @@
       <sourceFolder url="file://$MODULE_DIR$/src/androidTest/jni" isTestSource="true" />
       <sourceFolder url="file://$MODULE_DIR$/src/androidTest/rs" isTestSource="true" />
       <excludeFolder url="file://$MODULE_DIR$/build/intermediates/assets" />
-      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/bundles" />
+      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/blame" />
       <excludeFolder url="file://$MODULE_DIR$/build/intermediates/classes" />
-      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/coverage-instrumented-classes" />
       <excludeFolder url="file://$MODULE_DIR$/build/intermediates/dependency-cache" />
-      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/dex" />
-      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/dex-cache" />
+      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/exploded-aar/com.android.support/appcompat-v7/20.0.0/jars" />
+      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/exploded-aar/com.android.support/support-v4/20.0.0/jars" />
       <excludeFolder url="file://$MODULE_DIR$/build/intermediates/incremental" />
-      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/jacoco" />
-      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/javaResources" />
-      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/libs" />
-      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/lint" />
+      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/jniLibs" />
       <excludeFolder url="file://$MODULE_DIR$/build/intermediates/manifests" />
-      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/ndk" />
       <excludeFolder url="file://$MODULE_DIR$/build/intermediates/pre-dexed" />
-      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/proguard" />
       <excludeFolder url="file://$MODULE_DIR$/build/intermediates/res" />
       <excludeFolder url="file://$MODULE_DIR$/build/intermediates/rs" />
       <excludeFolder url="file://$MODULE_DIR$/build/intermediates/symbols" />
+      <excludeFolder url="file://$MODULE_DIR$/build/intermediates/transforms" />
       <excludeFolder url="file://$MODULE_DIR$/build/outputs" />
       <excludeFolder url="file://$MODULE_DIR$/build/tmp" />
     </content>
@@ -90,5 +89,4 @@
     <orderEntry type="library" exported="" name="support-annotations-20.0.0" level="project" />
     <orderEntry type="library" exported="" name="support-v4-20.0.0" level="project" />
   </component>
-</module>
-
+</module>
\ No newline at end of file
diff --git a/rabbit-escape-ui-android/build.gradle b/rabbit-escape-ui-android/build.gradle
index fc67c9c..a6fcfe1 100644
--- a/rabbit-escape-ui-android/build.gradle
+++ b/rabbit-escape-ui-android/build.gradle
@@ -5,7 +5,7 @@ buildscript {
         jcenter()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:1.0.0-rc2'
+        classpath 'com.android.tools.build:gradle:1.5.0'
 
         // NOTE: Do not place your application dependencies here; they belong
         // in the individual module build.gradle files
diff --git a/rabbit-escape-ui-android/rabbit-escape-ui-android.iml b/rabbit-escape-ui-android/rabbit-escape-ui-android.iml
index 5d611f7..4fd3c3e 100644
--- a/rabbit-escape-ui-android/rabbit-escape-ui-android.iml
+++ b/rabbit-escape-ui-android/rabbit-escape-ui-android.iml
@@ -4,10 +4,11 @@
     <facet type="java-gradle" name="Java-Gradle">
       <configuration>
         <option name="BUILD_FOLDER_PATH" value="$MODULE_DIR$/build" />
+        <option name="BUILDABLE" value="false" />
       </configuration>
     </facet>
   </component>
-  <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_1_6" inherit-compiler-output="false">
+  <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_1_6" inherit-compiler-output="true">
     <output url="file://$MODULE_DIR$/build/classes/main" />
     <output-test url="file://$MODULE_DIR$/build/classes/test" />
     <exclude-output />
@@ -17,5 +18,4 @@
     <orderEntry type="inheritedJdk" />
     <orderEntry type="sourceFolder" forTests="false" />
   </component>
-</module>
-
+</module>
\ No newline at end of file

```

**Comment by andybalaam** [comment]
I am convinced we should ignore the .idea directory. There is an idea plugin that uses the code formatting from Eclipse so I think we should set that up so we can share formatting.

**Comment by andybalaam** [comment]
Please check the updated instructions here https://github.com/andybalaam/rabbit-escape/wiki/Android-Studio , and if you can be bothered, delete your ~/Android/ directory, do a clean Git checkout, and check whether the instructions work.

That's what I've been doing, and it's slow and annoying, but it seems to work.

**Comment by andybalaam** [comment]
The updated instructions are based on my having removed .idea and the two .iml files.

**Comment by andybalaam** [comment]
@colonelfazackerley if this makes sense to you, please close this issue and #339.

**Comment by colonelfazackerley** [comment]
I am not suffering from git fighting problems any more. Starting to use studio from scratch should be tested. I could do this in a VM.

**Comment by andybalaam** [comment]
I have checked it from scratch but would appreciate you double checking and making sure the instructions make sense.

**Comment by andybalaam** [comment]
Last night I used iDEA for non-Android development and it worked ok without fighting so I'll leave the other `.idea` directories as they are until we find they cause problems.

**Comment by colonelfazackerley** [comment]
It's back. The project would not compile (from make or studio). Studio complains about something being too old, and offers to auto-fix. when i let it, it compiles.

Looking at the diff, it actually seems to be reverting to an older gradle.

If I undo this change, it wont compile.

```
diff --git a/rabbit-escape-ui-android/build.gradle b/rabbit-escape-ui-android/build.gradle
index 009b2d0..a6fcfe1 100644
--- a/rabbit-escape-ui-android/build.gradle
+++ b/rabbit-escape-ui-android/build.gradle
@@ -5,7 +5,7 @@ buildscript {
         jcenter()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:2.0.0-beta6'
+        classpath 'com.android.tools.build:gradle:1.5.0'
 
         // NOTE: Do not place your application dependencies here; they belong
         // in the individual module build.gradle files
```

**Comment by colonelfazackerley** [comment]
Looks like emulation is better in studio 2.0. Can I upgrade or will this cause problems?

**Comment by andybalaam** [comment]
Grr on gradle version thing. No idea what's wrong with that. Can you paste in the error message?

**Comment by andybalaam** [comment]
I think our policy on Android studio should be that we always use the latest available.

**Comment by colonelfazackerley** [comment]
I fire up studio from a console. The message below pops up. The "Plugin is too old" bit also appears in the "Messages" pane of studio, with a link "Fix plugin and sync project". If I follow that, it compiles again, but the build.gradle is changed.

```
[  22011]  ERROR - j.psi.stubs.StubTreeLoaderImpl - Outdated stub in index: no data, doc=null, docSaved=true, wasIndexedAlready=true, queried at 1436471820000 
[  22011]  ERROR - j.psi.stubs.StubTreeLoaderImpl - Outdated stub in index: no data, doc=null, docSaved=true, wasIndexedAlready=true, queried at 1436471820000 
[  22021]  ERROR - j.psi.stubs.StubTreeLoaderImpl - Android Studio 1.5.1  Build #AI-141.2456560 
[  22021]  ERROR - j.psi.stubs.StubTreeLoaderImpl - Android Studio 1.5.1  Build #AI-141.2456560 
[  22021]  ERROR - j.psi.stubs.StubTreeLoaderImpl - JDK: 1.7.0_95 
[  22021]  ERROR - j.psi.stubs.StubTreeLoaderImpl - JDK: 1.7.0_95 
[  22021]  ERROR - j.psi.stubs.StubTreeLoaderImpl - VM: OpenJDK 64-Bit Server VM 
[  22021]  ERROR - j.psi.stubs.StubTreeLoaderImpl - VM: OpenJDK 64-Bit Server VM 
[  22021]  ERROR - j.psi.stubs.StubTreeLoaderImpl - Vendor: Oracle Corporation 
[  22022]  ERROR - j.psi.stubs.StubTreeLoaderImpl - Vendor: Oracle Corporation 
[  22022]  ERROR - j.psi.stubs.StubTreeLoaderImpl - OS: Linux 
[  22022]  ERROR - j.psi.stubs.StubTreeLoaderImpl - OS: Linux 
[  22022]  ERROR - j.psi.stubs.StubTreeLoaderImpl - Last Action:  
[  22022]  ERROR - j.psi.stubs.StubTreeLoaderImpl - Last Action:  
[  31318]   WARN - inspections.IntellijLintClient - No projects found for [] 
[  32534]   WARN - nal.AbstractExternalSystemTask - Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to "2b5fd4d6d76e135e6cec5c5c18fc842f08a58fcc" 
com.intellij.openapi.externalSystem.model.LocationAwareExternalSystemException: Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to "2b5fd4d6d76e135e6cec5c5c18fc842f08a58fcc"
        at org.jetbrains.plugins.gradle.service.project.AbstractProjectImportErrorHandler.createUserFriendlyError(AbstractProjectImportErrorHandler.java:103)
        at org.jetbrains.plugins.gradle.service.project.BaseProjectImportErrorHandler.getUserFriendlyError(BaseProjectImportErrorHandler.java:158)
        at org.jetbrains.plugins.gradle.service.project.BaseGradleProjectResolverExtension.getUserFriendlyError(BaseGradleProjectResolverExtension.java:438)
        at com.android.tools.idea.gradle.project.AndroidGradleProjectResolver.getUserFriendlyError(AndroidGradleProjectResolver.java:348)
        at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:164)
        at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:366)
        at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:332)
        at org.jetbrains.plugins.gradle.service.project.GradleExecutionHelper.execute(GradleExecutionHelper.java:225)
        at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:97)
        at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:65)
        at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:41)
        at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:37)
        at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:59)
        at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
        at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:49)
        at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:51)
        at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:138)
        at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:124)
        at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4.execute(ExternalSystemUtil.java:540)
        at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$5$2.run(ExternalSystemUtil.java:621)
        at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
        at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
        at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
        at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

[  32538]   WARN - radle.project.ProjectSetUpTask -  
[  35121]   WARN - inspections.IntellijLintClient - No projects found for [] 
[  44704]   WARN - inspections.IntellijLintClient - No projects found for [] 
```

**Comment by colonelfazackerley** [comment]
I upgraded studio. now the diff looks more sensible.
```
diff --git a/rabbit-escape-ui-android/build.gradle b/rabbit-escape-ui-android/build.gradle
index 009b2d0..cb98401 100644
--- a/rabbit-escape-ui-android/build.gradle
+++ b/rabbit-escape-ui-android/build.gradle
@@ -5,7 +5,7 @@ buildscript {
         jcenter()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:2.0.0-beta6'
+        classpath 'com.android.tools.build:gradle:2.0.0'
 
         // NOTE: Do not place your application dependencies here; they belong
         // in the individual module build.gradle files
```

**Comment by colonelfazackerley** [comment]
I reverted the build.gradle to the ...beta6 one, and the problem is gone. I guess those versions are very similar.

**Comment by colonelfazackerley** [comment]
oh, maybe it's not. it seems to silently remove the beta6

**Comment by andybalaam** [comment]
I now get the same error message.  I am confused.

**Comment by andybalaam** [comment]
Removing beta6 seems right though, if the final release is out.

**Comment by andybalaam** [comment]
I think the more recent version of gradle somehow requires a more recent version of the Android SDK.

**Comment by colonelfazackerley** [comment]
An aside:

With upgraded studio, using an android emulator is easy. After the first use, it is extremely quick too.

Couple of glitches
- there is a floating button panel that does not seem to work and keeps dissappearing. however, hovering over the buttons reveals the keyboard shortcuts, and they work.
- sound does not seem to work.

However, overall it is a pleasure to use.

**Comment by colonelfazackerley** [comment]
installing "mesa-utils" for "glxinfo" seems to have got the sound working.

**Comment by andybalaam** [comment]
Please add to the wiki, if you haven't

**Comment by colonelfazackerley** [comment]
Can you test too first? Might just be some quirk of my hardware.

**Comment by andybalaam** [comment]
Yes, when I get a chance. Last time I tried it wouldn't work at all. Annoying time waste.

**Comment by colonelfazackerley** [comment]
It was seemless for me. just a few clicks. I think the significant change is the upgrade to the newest version of studio. They seem to have put a lot of work into making the emulators easier to use in development.

its much faster, as you dont need to wait for the new jar to get pushed down the USB to your droid.

**Comment by andybalaam** [comment]
I think I'll start fresh. It sounds good.

**Comment by andybalaam** [comment]
This seems ok at the moment.  Let's open a new ticket if needed.
