### ISSUE TITLE
ConcurrentModificationException when resizing window with water in it

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#442]
Start a level in Swing with some water visible, e.g.:

    $ ./runrabbit swing -l ./rabbit-escape-engine/src/rabbitescape/levels/staging/smallworld/Dambusters.rel

Make sure you can see some water, then resize the window.  The screen will flicker, and in the console you will see:

```
Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at rabbitescape.ui.swing.SwingGraphics$DrawFrame.drawPolygons(SwingGraphics.java:150)
	at rabbitescape.ui.swing.SwingGraphics$DrawFrame.draw(SwingGraphics.java:93)
	at rabbitescape.ui.swing.BufferedDraw.run(BufferedDraw.java:43)
	at rabbitescape.ui.swing.SwingGraphics.redraw(SwingGraphics.java:249)
	at rabbitescape.ui.swing.MainJFrame$Listener.componentResized(MainJFrame.java:59)
	at java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:159)
	at java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:159)
	at java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:159)
	at java.awt.Component.processComponentEvent(Component.java:6342)
	at java.awt.Component.processEvent(Component.java:6296)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Window.processEvent(Window.java:2022)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by colonelfazackerley** [comment]
I may need some help here. using Collections.synchronizedList() and declaring SwingGraphics.drawPolygons() synchronized don't work.

**Comment by andybalaam** [comment]
I'm not sure what is going on yet - will need to investigate. I think the whole swing window and game loop needs an overhaul.
