### ISSUE TITLE
Crash when you pause with a rabbit off-screen

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#456]
- Encourage a rabbit to go off-screen.
- Pause while it dies.
- Notice a crash with this stack trace:
```
java.lang.IndexOutOfBoundsException: Index: 9, Size: 9
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at rabbitescape.engine.util.LookupTable2D.getItemsAt(LookupTable2D.java:99)
	at rabbitescape.render.Overlay.at(Overlay.java:32)
	at rabbitescape.ui.swing.SwingGraphics$DrawFrame.tacticalOverlay(SwingGraphics.java:127)
	at rabbitescape.ui.swing.SwingGraphics$DrawFrame.draw(SwingGraphics.java:104)
	at rabbitescape.ui.swing.BufferedDraw.run(BufferedDraw.java:43)
	at rabbitescape.ui.swing.SwingGraphics.draw(SwingGraphics.java:222)
	at rabbitescape.render.gameloop.GameLoop.step(GameLoop.java:71)
	at rabbitescape.render.gameloop.GameLoop.run(GameLoop.java:51)
	at rabbitescape.ui.swing.SwingGameLaunch.run(SwingGameLaunch.java:167)
	at rabbitescape.render.SingleGameEntryPoint.launchGame(SingleGameEntryPoint.java:54)
	at rabbitescape.render.SingleGameEntryPoint.run(SingleGameEntryPoint.java:37)
	at rabbitescape.ui.swing.SwingSingleGameEntryPoint.go(SwingSingleGameEntryPoint.java:121)
	at rabbitescape.ui.swing.SwingSingleGameEntryPoint.entryPoint(SwingSingleGameEntryPoint.java:59)
	at rabbitescape.ui.swing.SwingMain.main(SwingMain.java:46)
```

**Comment by andybalaam** [comment]
I am working on this.
