### ISSUE TITLE
"until:WON" not supported in command-line solution

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#551]
When I use `until:WON` inside a solution that I pass on the command line, rabbit escape crashes.

```
$ ./runrabbit swing -l rabbit-escape-engine/src/rabbitescape/levels/08_rabbots/20_GCD.rel -s 'dig;51;(6,0);until:WON'
rabbitescape.engine.solution.InvalidAction: solution.InvalidAction {action=pGIk}@=! hc?#yh!%8Z{!B, cause=null}
	at rabbitescape.engine.solution.SolutionParser.doMakeAction(SolutionParser.java:114)
	at rabbitescape.engine.solution.SolutionParser.makeAction(SolutionParser.java:74)
	at rabbitescape.engine.solution.SolutionParser.parseCommand(SolutionParser.java:55)
	at rabbitescape.engine.solution.SolutionParser.parse(SolutionParser.java:38)
	at rabbitescape.engine.solution.SolutionDemo.<init>(SolutionDemo.java:42)
	at rabbitescape.ui.swing.SwingGameLaunch.createSolutionInterpreter(SwingGameLaunch.java:152)
	at rabbitescape.ui.swing.SwingGameLaunch.<init>(SwingGameLaunch.java:88)
	at rabbitescape.ui.swing.SwingSingleGameEntryPoint.createGameLaunch(SwingSingleGameEntryPoint.java:134)
	at rabbitescape.render.SingleGameEntryPoint.launchGame(SingleGameEntryPoint.java:52)
	at rabbitescape.render.SingleGameEntryPoint.run(SingleGameEntryPoint.java:37)
	at rabbitescape.ui.swing.SwingSingleGameEntryPoint.go(SwingSingleGameEntryPoint.java:122)
	at rabbitescape.ui.swing.SwingSingleGameEntryPoint.entryPoint(SwingSingleGameEntryPoint.java:80)
	at rabbitescape.ui.swing.SwingMain.main(SwingMain.java:47)
```

The same solution works fine when in a .rel file.  It should work fine on the command line.

**Comment by tttppp** [comment]
I didn't even know it was possible to pass a solution like this - awesome!

**Comment by andybalaam** [comment]
Yes, it is rather good.

**Comment by GamingInky** [comment]
I didn't know either
