### ISSUE TITLE
Smoke test fails

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#614]
The test `test_Smoke" fails for me with the latest code.

```
$ adb shell am instrument -w -r   -e debug false -e class 'rabbitescape.ui.android.SmokeTest' net.artificialworlds.rabbitescapefree.test/android.test.InstrumentationTestRunner
Client not ready yet..
Started running tests

junit.framework.ComparisonFailure: expected:<[Medium]> but was:<[${number} Placement]>
at rabbitescape.ui.android.AndroidUiDriver.clickMenuItem(AndroidUiDriver.java:97)
at rabbitescape.ui.android.SmokeTest.test_Smoke(SmokeTest.java:31)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1584)
```

**Comment by andybalaam** [comment]
It complains that the menu item in position 1 is not "Medium", but "Placement".  When I watch the test I see that the menu item is indeed "Medium", so I suspect we have a reference to the wrong Activity or ListView somehow,
